//
// Generated file, do not edit! Created by nedtool 5.2 from udp/UDPControlInfo.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __UDPCONTROLINFO_M_H
#define __UDPCONTROLINFO_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../3rdParty/IPv4Address.h"
#include "../3rdParty/IPv6Address.h"
// }}

/**
 * Class generated from <tt>udp/UDPControlInfo.msg:29</tt> by nedtool.
 * <pre>
 * message UDPControlInfo
 * {
 *     inet::IPv4Address srcIPv4;	// source IPv4 address
 *     inet::IPv6Address srcIPv6;	// source IPv6 address
 *     int srcPort;					// source port
 * 
 *     inet::IPv4Address destIPv4;	// destination IPv4 address
 *     inet::IPv6Address destIPv6;	// destination IPv6 address
 *     int destPort;				// destination port
 * }
 * </pre>
 */
class UDPControlInfo : public ::omnetpp::cMessage
{
  protected:
    inet::IPv4Address srcIPv4;
    inet::IPv6Address srcIPv6;
    int srcPort;
    inet::IPv4Address destIPv4;
    inet::IPv6Address destIPv6;
    int destPort;

  private:
    void copy(const UDPControlInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UDPControlInfo&);

  public:
    UDPControlInfo(const char *name=nullptr, short kind=0);
    UDPControlInfo(const UDPControlInfo& other);
    virtual ~UDPControlInfo();
    UDPControlInfo& operator=(const UDPControlInfo& other);
    virtual UDPControlInfo *dup() const override {return new UDPControlInfo(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual inet::IPv4Address& getSrcIPv4();
    virtual const inet::IPv4Address& getSrcIPv4() const {return const_cast<UDPControlInfo*>(this)->getSrcIPv4();}
    virtual void setSrcIPv4(const inet::IPv4Address& srcIPv4);
    virtual inet::IPv6Address& getSrcIPv6();
    virtual const inet::IPv6Address& getSrcIPv6() const {return const_cast<UDPControlInfo*>(this)->getSrcIPv6();}
    virtual void setSrcIPv6(const inet::IPv6Address& srcIPv6);
    virtual int getSrcPort() const;
    virtual void setSrcPort(int srcPort);
    virtual inet::IPv4Address& getDestIPv4();
    virtual const inet::IPv4Address& getDestIPv4() const {return const_cast<UDPControlInfo*>(this)->getDestIPv4();}
    virtual void setDestIPv4(const inet::IPv4Address& destIPv4);
    virtual inet::IPv6Address& getDestIPv6();
    virtual const inet::IPv6Address& getDestIPv6() const {return const_cast<UDPControlInfo*>(this)->getDestIPv6();}
    virtual void setDestIPv6(const inet::IPv6Address& destIPv6);
    virtual int getDestPort() const;
    virtual void setDestPort(int destPort);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UDPControlInfo& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UDPControlInfo& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UDPCONTROLINFO_M_H

