//
// Generated file, do not edit! Created by nedtool 5.2 from app/HTTPServerMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __HTTPSERVERMSG_M_H
#define __HTTPSERVERMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>app/HTTPServerMsg.msg:20</tt> by nedtool.
 * <pre>
 * packet HTTPServerMsg
 * {
 *     string response;
 * }
 * </pre>
 */
class HTTPServerMsg : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string response;

  private:
    void copy(const HTTPServerMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HTTPServerMsg&);

  public:
    HTTPServerMsg(const char *name=nullptr, short kind=0);
    HTTPServerMsg(const HTTPServerMsg& other);
    virtual ~HTTPServerMsg();
    HTTPServerMsg& operator=(const HTTPServerMsg& other);
    virtual HTTPServerMsg *dup() const override {return new HTTPServerMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getResponse() const;
    virtual void setResponse(const char * response);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HTTPServerMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HTTPServerMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __HTTPSERVERMSG_M_H

